name: 'Extract Docker Digest'
description: 'Extract digest from docker build or bake output'

inputs:
  mode:
    description: 'Build mode: build or bake'
    required: true
  build_digest:
    description: '[build mode] Digest output from docker/build-push-action'
    required: false
    default: ''
  bake_metadata:
    description: '[bake mode] Metadata output from docker/bake-action'
    required: false
    default: ''
  bake_target:
    description: '[bake mode] Target name to extract digest for'
    required: false
    default: ''
  output_file:
    description: 'Path to write the digest'
    required: true

outputs:
  digest:
    description: 'The extracted digest'
    value: ${{ steps.extract.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Extract digest
      id: extract
      shell: bash
      run: |
        OUTPUT_FILE="${{ inputs.output_file }}"
        
        if [[ "${{ inputs.mode }}" == "build" ]]; then
          # Use quoted heredoc to safely write digest without bash expansion
          cat <<'DIGEST_EOF' > "$OUTPUT_FILE"
        ${{ inputs.build_digest }}
        DIGEST_EOF
        elif [[ "${{ inputs.mode }}" == "bake" ]]; then
          # Write metadata to temp file using quoted heredoc
          METADATA_FILE="${OUTPUT_FILE%.txt}-metadata.json"
          cat <<'METADATA_EOF' > "$METADATA_FILE"
        ${{ inputs.bake_metadata }}
        METADATA_EOF
          # Extract digest from metadata JSON
          jq -r '.["${{ inputs.bake_target }}"]["containerimage.digest"]' "$METADATA_FILE" > "$OUTPUT_FILE"
        fi
        
        # Read and output the digest
        digest=$(cat "$OUTPUT_FILE")
        echo "digest=$digest" >> $GITHUB_OUTPUT
        echo "Extracted digest: $digest"

