name: 'Docker Setup'
description: 'Setup Docker build environment (checkout, QEMU, buildx)'

inputs:
  use_qemu:
    description: 'Set up QEMU for cross-platform builds'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v4

    - name: Set up QEMU
      if: inputs.use_qemu == 'true'
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a # v3
