name: 'GCP Docker Auth'
description: 'Authenticate to GCP and configure Docker for Artifact Registry'

inputs:
  gcp_project_id:
    description: 'GCP Project ID for workload identity federation'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@fc2174804b84f912b1f6d334e9463f484f1c552d # v3
      with:
        project_id: ${{ inputs.gcp_project_id }}
        workload_identity_provider: projects/${{ inputs.gcp_project_id }}/locations/global/workloadIdentityPools/github/providers/github-oidc
        create_credentials_file: true

    - name: Configure Docker for GCP Artifact Registry
      shell: bash
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

